// Harbour network track data. Positions are in SVG viewBox units (1580 × 1064 for the map).
import type { ArchEdge } from "@/lib/architecture/types";

// Long runs use dedicated lanes so nothing overlaps:
// left gutter 412 (health checks) · 438 (run.app bypass)
// right gutter 1084 · 1106 · 1128 · 1150 · 1172 · 1188
// bottom lanes 990 · 1014
export const edges: ArchEdge[] = [
  {
    from: "USERS",
    to: "CF",
    fromSide: "b",
    toSide: "t",
    tone: "edge",
    layers: ["ingress", "lb"],
  },
  {
    from: "ADMIN",
    to: "CF",
    fromSide: "t",
    toSide: "b",
    tone: "edge",
    layers: ["ingress"],
  },
  {
    from: "CF",
    to: "GLB",
    fromSide: "r",
    toSide: "l",
    label: "origin fetch",
    tone: "edge",
    layers: ["ingress", "lb"],
  },
  {
    from: "GLB",
    to: "API",
    fromSide: "r",
    toSide: "l",
    label: "serverless NEG",
    tone: "edge",
    layers: ["ingress", "lb"],
  },
  {
    from: "USERS",
    to: "DIRECT",
    fromSide: "r",
    toSide: "l",
    tone: "danger",
    dashed: true,
    layers: ["ingress", "defects"],
    defect: true,
    closedBy: "D6",
  },
  {
    from: "DIRECT",
    to: "API",
    fromSide: "r",
    toSide: "l",
    toOffset: 8,
    via: [
      { x: 438, y: 214 },
      { x: 438, y: 268 },
    ],
    tone: "danger",
    dashed: true,
    layers: ["ingress", "defects"],
    defect: true,
    closedBy: "D6",
  },
  {
    from: "HC",
    to: "G_APP",
    fromSide: "r",
    toSide: "t",
    via: [
      { x: 412, y: 644 },
      { x: 412, y: 192 },
      { x: 756, y: 192 },
    ],
    label: "probes · needs a firewall rule",
    tone: "edge",
    layers: ["lb", "firewall"],
  },
  {
    from: "SCHED",
    to: "JOBS",
    fromSide: "r",
    toSide: "l",
    tone: "edge",
    layers: ["ingress"],
  },
  {
    from: "IAP",
    to: "BASTION",
    fromSide: "r",
    toSide: "l",
    label: "tunnelled SSH",
    tone: "edge",
    dashed: true,
    dim: true,
    layers: ["ingress", "access"],
    changedBy: {
      defect: "D2",
      set: { tone: "compute", dim: false, dashed: false },
    },
  },
  {
    from: "ILB",
    to: "LEGACY",
    fromSide: "t",
    toSide: "b",
    tone: "edge",
    dim: true,
    layers: ["ingress", "lb"],
    changedBy: { defect: "D12", set: { dim: false } },
  },
  {
    from: "WORKER",
    to: "RABBIT",
    fromSide: "b",
    toSide: "t",
    toOffset: 200,
    via: [
      { x: 759, y: 404 },
      { x: 974, y: 404 },
    ],
    label: "consume",
    tone: "compute",
    layers: ["firewall"],
  },
  {
    from: "LEGACY",
    to: "SQL",
    fromSide: "r",
    toSide: "l",
    via: [
      { x: 1084, y: 288 },
      { x: 1084, y: 225 },
    ],
    label: "public internet",
    tone: "danger",
    dashed: true,
    layers: ["private", "defects"],
    defect: true,
    closedBy: "D5",
  },
  {
    from: "G_APP",
    to: "GCS",
    fromSide: "r",
    toSide: "l",
    via: [
      { x: 1106, y: 315 },
      { x: 1106, y: 461 },
    ],
    label: "PGA",
    tone: "private",
    layers: ["private"],
  },
  {
    from: "PSA",
    to: "REDIS",
    fromSide: "b",
    toSide: "l",
    via: [
      { x: 606, y: 1014 },
      { x: 1172, y: 1014 },
      { x: 1172, y: 288 },
    ],
    label: "peering · private IP",
    tone: "private",
    layers: ["private"],
  },
  {
    from: "PSA",
    to: "SQL",
    fromSide: "b",
    toSide: "l",
    via: [
      { x: 606, y: 990 },
      { x: 1084, y: 990 },
      { x: 1084, y: 225 },
    ],
    label: "private IP via PSA",
    tone: "private",
    layers: ["private"],
    opensWith: "D5",
  },
  {
    from: "PSC",
    to: "SAAS",
    fromSide: "r",
    toSide: "l",
    toOffset: 44,
    via: [
      { x: 1120, y: 952 },
      { x: 1120, y: 842 },
    ],
    label: "endpoint",
    tone: "private",
    layers: ["private"],
  },
  {
    from: "NAT",
    to: "PAY",
    fromSide: "r",
    toSide: "l",
    via: [
      { x: 1128, y: 880 },
      { x: 1128, y: 598 },
    ],
    label: "stable IP",
    tone: "edge",
    layers: ["egress"],
  },
  {
    from: "NAT",
    to: "FCM",
    fromSide: "r",
    toSide: "l",
    via: [
      { x: 1150, y: 880 },
      { x: 1150, y: 725 },
    ],
    tone: "edge",
    layers: ["egress"],
  },
  {
    from: "ONPREM",
    to: "VPN",
    fromSide: "r",
    toSide: "l",
    tone: "data",
    dim: true,
    layers: ["routing"],
  },
  {
    from: "VPN",
    to: "SNB",
    fromSide: "r",
    toSide: "l",
    tone: "data",
    dashed: true,
    dim: true,
    layers: ["routing"],
  },
  {
    from: "PARTNER",
    to: "PEER",
    fromSide: "r",
    toSide: "l",
    tone: "data",
    layers: ["routing"],
  },
  {
    from: "PEER",
    to: "PSA",
    fromSide: "r",
    toSide: "l",
    tone: "danger",
    dashed: true,
    layers: ["routing", "defects"],
    defect: true,
    closedBy: "D11",
  },
];
