// Harbour network track data. Positions are in SVG viewBox units (1580 × 1064 for the map).
import type { ArchGroup } from "@/lib/architecture/types";

export const groups: ArchGroup[] = [
  {
    id: "G_POL",
    x: 448,
    y: 8,
    w: 616,
    h: 40,
    label: "organization / folder firewall policies",
    sub: "none exist - nothing sets a floor above the project",
    tone: "danger",
    dashed: true,
    layers: ["firewall", "defects"],
    defects: ["D10"],
  },
  {
    id: "G_VPC",
    x: 448,
    y: 80,
    w: 616,
    h: 954,
    label: "harbour-vpc",
    sub: "custom mode · allow-all ingress, no egress rules",
    tone: "lineStrong",
    layers: ["all", "firewall", "defects"],
    defects: ["D1", "D9"],
  },
  {
    id: "G_REGA",
    x: 464,
    y: 150,
    w: 584,
    h: 566,
    label: "asia-southeast1 · primary",
    tone: "lineStrong",
  },
  {
    id: "G_APP",
    x: 478,
    y: 212,
    w: 556,
    h: 206,
    label: "sn-a-app",
    sub: "10.10.0.0/20 · PGA on",
    tone: "compute",
    layers: ["firewall", "private", "lb"],
  },
  {
    id: "G_MGMT",
    x: 478,
    y: 498,
    w: 272,
    h: 116,
    label: "sn-a-mgmt",
    sub: "10.10.16.0/24 · PGA on",
    tone: "compute",
    layers: ["firewall"],
  },
  {
    id: "G_DATA",
    x: 762,
    y: 498,
    w: 272,
    h: 116,
    label: "sn-a-data",
    sub: "10.10.17.0/24 · PGA OFF",
    tone: "danger",
    layers: ["firewall", "private", "defects"],
    defects: ["D4"],
  },
  {
    id: "G_PROXY",
    x: 478,
    y: 630,
    w: 556,
    h: 62,
    label: "sn-a-proxy",
    sub: "10.10.250.0/24 · proxy-only - never created",
    tone: "danger",
    dashed: true,
    layers: ["defects", "lb"],
    defects: ["D12"],
  },
  {
    id: "G_REGB",
    x: 464,
    y: 736,
    w: 584,
    h: 98,
    label: "asia-south1 · secondary",
    tone: "line",
    dashed: true,
    dim: true,
  },
  {
    id: "G_MANAGED",
    x: 1200,
    y: 150,
    w: 352,
    h: 210,
    label: "Google-managed tenant",
    sub: "where Cloud SQL and Memorystore run",
    tone: "data",
    layers: ["private"],
  },
  {
    id: "G_APIS",
    x: 1200,
    y: 384,
    w: 352,
    h: 116,
    label: "Google APIs",
    sub: "reached by PGA or a PSC endpoint",
    tone: "data",
    layers: ["private"],
  },
  {
    id: "G_EXT",
    x: 1200,
    y: 524,
    w: 352,
    h: 250,
    label: "internet · third parties",
    tone: "external",
    layers: ["egress"],
  },
];
