// Harbour network track data.
import type { Journey } from "@/lib/architecture/types";

export const journeys: Journey[] = [
  {
    title: "A shopper loads a product page",
    shortTitle: "Product page",
    summary: "internet → Cloudflare → ALB → harbour-api → database",
    path: ["USERS", "CF", "GLB", "API", "SQL"],
    context: ["G_VPC", "G_REGA", "G_APP", "G_MANAGED", "GCS"],
    switchAt: "D5",
    pathAfter: ["USERS", "CF", "GLB", "API", "PSA", "SQL"],
    contextAfter: ["G_VPC", "G_REGA", "G_APP", "G_MANAGED", "GCS"],
    hops: [
      {
        at: "CF",
        whileOpen: "D8",
        where: "Cloudflare",
        what: "TLS terminates at the edge, WAF rules run, cached assets are served",
        why: "Nothing has touched your VPC yet",
      },
      {
        at: "CF",
        afterClosed: "D8",
        where: "Cloudflare",
        what: "Same work, but now the only way in — the load balancer accepts only Cloudflare’s published ranges",
        why: "Bypassing the CDN no longer reaches the origin",
      },
      {
        at: "GLB",
        whileOpen: "D8",
        where: "forwarding rule",
        what: "The request arrives at 34.120.95.195:443 and enters the load balancer",
        why: "The LB accepts connections from any source, so the CDN and its WAF can be skipped entirely",
        fails: true,
        fixedBy: "D8",
      },
      {
        at: "GLB",
        afterClosed: "D8",
        where: "forwarding rule",
        what: "Same entry point, now behind a Cloud Armor rule allowing only the cloudflare-edge address group",
        why: "The address group tracks the provider’s ranges, so the lock does not go stale",
      },
      {
        at: "GLB",
        whileOpen: "D15",
        where: "target proxy",
        what: "TLS terminates a second time, at the load balancer",
        why: "No SSL policy is set, so it will negotiate older TLS versions with any client that asks",
        fails: true,
        fixedBy: "D15",
      },
      {
        at: "GLB",
        afterClosed: "D15",
        where: "target proxy",
        what: "TLS terminates with a minimum of 1.2 and a restricted cipher profile",
        why: "Everything about TLS lives on this one object — certificate, policy, mTLS",
      },
      {
        at: "GLB",
        where: "URL map",
        what: "Host and path are read, and the request is sent to api-backend-service",
        why: "/static/* would have gone to the backend bucket instead",
      },
      {
        at: "GLB",
        where: "backend service",
        what: "Cloud Armor inspects the request, then it goes to the serverless NEG",
        why: "This is the only place the WAF exists — it attaches here, not to the load balancer",
      },
      {
        at: "API",
        whileOpen: "D6",
        where: "harbour-api",
        what: "Cloud Run handles the request — and its run.app URL answers the internet too",
        why: "Everything above is real and every bit of it can be walked around",
        fails: true,
        fixedBy: "D6",
      },
      {
        at: "API",
        afterClosed: "D6",
        where: "harbour-api",
        what: "Cloud Run handles the request. Ingress is internal-and-cloud-load-balancing, so the LB is the only door",
        why: "The source IP it sees is the load balancer’s; the real client is in X-Forwarded-For",
      },
      {
        at: "SQL",
        whileOpen: "D5",
        where: "to the database",
        what: "The database has a public IP, so this is not a private destination",
        why: "The query crosses the public internet and is admitted by the authorized-networks list",
        fails: true,
        fixedBy: "D5",
      },
      {
        at: "PSA",
        afterClosed: "D5",
        where: "PSA peering",
        what: "The database now holds a private IP from the reserved 10.90.0.0/16 range",
        why: "The peering already existed — Redis was using it. Only the database had to be pointed at it.",
      },
      {
        at: "SQL",
        afterClosed: "D5",
        where: "to the database",
        what: "The query never leaves the VPC, and the authorized-networks list is gone",
        why: "No public IP, no allow-list to maintain, no home broadband addresses in production config",
      },
    ],
  },
  {
    title: "A health check probe arrives",
    shortTitle: "Health probe",
    summary: "Google probe range → firewall → legacy-api VM",
    path: ["HC", "G_APP", "LEGACY"],
    context: ["G_VPC", "G_REGA", "ILB", "G_PROXY"],
    hops: [
      {
        at: "HC",
        where: "35.191.0.0/16",
        what: "Google opens a connection to the probe port on each MIG instance",
        why: "The probe does not come from the load balancer and does not come from your VPC",
      },
      {
        at: "G_APP",
        where: "firewall",
        what: "allow-health-check permits the two probe ranges to VMs tagged lb-health-check",
        why: "Without this rule every backend reads unhealthy while the app works perfectly",
      },
      {
        at: "LEGACY",
        whileOpen: "D13",
        where: "legacy-api VM",
        what: "A TCP connection to port 80 succeeds",
        why: "Healthy. But this proves only that something holds the port open.",
      },
      {
        at: "LEGACY",
        whileOpen: "D13",
        where: "a hung instance",
        what: "Still accepting TCP, still returning 500 to every request",
        why: "It passes, stays in rotation, and the autohealer leaves it alone because it uses the same check",
        fails: true,
        fixedBy: "D13",
      },
      {
        at: "LEGACY",
        afterClosed: "D13",
        where: "legacy-api VM",
        what: "An HTTP GET to /health returns 200",
        why: "This proves the application is actually responding, not just that a port is open",
      },
      {
        at: "LEGACY",
        afterClosed: "D13",
        where: "a hung instance",
        what: "/health returns 500, so the probe fails three times running",
        why: "It leaves rotation, and the autohealer replaces it — one setting fixing both",
      },
    ],
  },
  {
    title: "The API charges a card",
    shortTitle: "Card charge",
    summary: "harbour-api → PayGate, which whitelists your IP",
    path: ["API", "NAT", "PAY"],
    context: [
      "USERS",
      "CF",
      "GLB",
      "G_VPC",
      "G_REGA",
      "G_APP",
      "ROUTER",
      "G_EXT",
      "BILL",
      "FCM",
    ],
    hops: [
      {
        at: "API",
        where: "harbour-api",
        what: "Opens a connection to PayGate over HTTPS",
        why: "PayGate is a public address, not an RFC 1918 range",
      },
      {
        at: "API",
        whileOpen: "D7",
        where: "egress decision",
        what: "private-ranges-only means internet traffic does not enter the VPC",
        why: "It leaves through Google’s shared serverless pool instead",
        fails: true,
        fixedBy: "D7",
      },
      {
        at: "API",
        afterClosed: "D7",
        where: "egress decision",
        what: "all-traffic sends everything through the VPC, internet included",
        why: "Now the call follows your routes like any other VPC traffic",
      },
      {
        at: "NAT",
        whileOpen: "D7",
        where: "Cloud NAT",
        what: "Never involved, because the traffic never reached the VPC",
        why: "The stable egress address exists and is simply not on this path",
        fails: true,
      },
      {
        at: "NAT",
        afterClosed: "D7",
        where: "Cloud NAT",
        what: "Translates the source to one of the two manually reserved addresses",
        why: "Manual rather than automatic, precisely so the address is stable enough to register",
      },
      {
        at: "PAY",
        whileOpen: "D7",
        where: "source IP at PayGate",
        what: "A random Google address that changes constantly",
        why: "Not on the whitelist, so the charge is rejected",
        fails: true,
      },
      {
        at: "PAY",
        afterClosed: "D7",
        where: "source IP at PayGate",
        what: "One of the two reserved NAT addresses, every time",
        why: "The whitelist holds, and it keeps holding across redeploys and scale events",
      },
    ],
  },
  {
    title: "The nightly job runs",
    shortTitle: "Nightly job",
    summary: "Cloud Scheduler → harbour-jobs → broker + Secret Manager",
    path: ["SCHED", "JOBS", "SECRET", "RABBIT", "G_DATA"],
    context: ["G_VPC", "G_REGA", "G_APP", "G_DATA", "G_APIS", "GCS"],
    hops: [
      {
        at: "SCHED",
        where: "Cloud Scheduler",
        what: "Fires an authenticated request with an OIDC token",
        why: "Ingress on the job service is internal-and-cloud-load-balancing, so the public URL is closed",
      },
      {
        at: "SECRET",
        where: "harbour-jobs",
        what: "Reads credentials from Secret Manager",
        why: "Its subnet has PGA on, so this works with no external IP",
      },
      {
        at: "RABBIT",
        where: "to the broker",
        what: "Publishes work onto rabbitmq-1 at 10.10.17.x",
        why: "Two firewall checks: the job service’s egress, then the broker’s ingress",
      },
      {
        at: "G_DATA",
        whileOpen: "D4",
        where: "broker side effect",
        what: "The broker tries to write its own logs",
        why: "sn-a-data has PGA off and the VM has no external IP, so it cannot reach the logging API at all",
        fails: true,
        fixedBy: "D4",
      },
      {
        at: "G_DATA",
        afterClosed: "D4",
        where: "broker side effect",
        what: "The broker writes its logs over Private Google Access",
        why: "One subnet flag. Doing half of the no-external-IP design was worse than doing none of it.",
      },
    ],
  },
  {
    title: "An engineer opens an SSH session",
    shortTitle: "SSH session",
    summary: "laptop → public IP → bastion",
    summaryAfter: "laptop → IAP tunnel → VM, no public IP anywhere",
    path: ["IAP", "BASTION", "RABBIT"],
    context: ["G_VPC", "G_REGA", "G_MGMT", "G_DATA", "G_APP"],
    switchAt: "D3a",
    noteAfter:
      "Not the same route made to work. The bastion stops being a box you reach and becomes a box you are tunnelled into — its public address is deleted, not narrowed.",
    hops: [
      {
        at: "BASTION",
        whileOpen: "D2",
        where: "as found",
        what: "The bastion has an external IP and port 22 is open to 0.0.0.0/0",
        why: "Anyone on the internet can attempt authentication. The only thing between them and a shell is the key.",
        fails: true,
        fixedBy: "D2",
      },
      {
        at: "IAP",
        where: "gcloud",
        what: "--tunnel-through-iap authenticates you to Google first",
        why: "Access is decided by who you are, not by whether you can reach an IP",
      },
      {
        at: "IAP",
        where: "IAP",
        what: "Checks whether your identity holds roles/iap.tunnelResourceAccessor",
        why: "roles/editor does not include it. This is the check people assume their broad access covers.",
      },
      {
        at: "IAP",
        where: "35.235.240.0/20",
        what: "An encrypted tunnel opens to the VM’s port 22 from IAP’s own fixed range",
        why: "The firewall allows only this range, and traffic originates here only after the identity check passed",
      },
      {
        at: "BASTION",
        whileOpen: "D16",
        where: "the VM",
        what: "The VM still decides who may log in, and as which user",
        why: "Metadata SSH keys, so the log records that a key was used, not who used it",
        fails: true,
        fixedBy: "D16",
      },
      {
        at: "BASTION",
        afterClosed: "D16",
        where: "the VM",
        what: "OS Login derives the Linux user from your Google identity",
        why: "Revoking roles/compute.osLogin removes access to every VM at once, and the log names the person",
      },
      {
        at: "BASTION",
        afterClosed: "D3a",
        where: "no public address",
        what: "The external IP is gone entirely",
        why: "IAP covers inbound, PGA covers Google APIs, Cloud NAT covers the internet. All three, or none of it works.",
      },
      {
        where: "when it fails",
        what: "The API, the role and the firewall rule must all three be true",
        why: "Miss one and it fails, often looking like a different problem. --troubleshoot checks all three at once.",
      },
      {
        at: "RABBIT",
        where: "onward",
        what: "From this VM to rabbitmq-1 on 22",
        why: "Still two firewall checks. Being inside the VPC grants nothing on its own.",
      },
    ],
  },
  {
    title: "The partner network reaches the database",
    shortTitle: "Partner → DB",
    summary: "partner-vpc → peering → harbour-vpc → ✗",
    summaryAfter: "partner-vpc → its own PSC endpoint → published service",
    path: ["PARTNER", "PEER", "PSA", "REDIS"],
    context: ["G_VPC", "G_MANAGED", "PSC", "SQL"],
    switchAt: "D11",
    pathAfter: ["PARTNER", "PSC", "REDIS"],
    contextAfter: ["G_VPC", "G_MANAGED", "PEER", "SQL", "PSA"],
    noteAfter:
      "A different design, not the same path repaired. The peering stays for what it is good at; the database is reached by a path of its own.",
    hops: [
      {
        at: "PARTNER",
        whileOpen: "D11",
        where: "partner-vpc",
        what: "Sends traffic to the Redis private IP in 10.90.0.0/16",
        why: "The partner is peered to your VPC and assumes that is enough",
      },
      {
        at: "PEER",
        whileOpen: "D11",
        where: "peering",
        what: "Peering carries traffic between the two directly connected VPCs",
        why: "Your subnet routes are shared with them, so they can reach your VMs",
      },
      {
        at: "PSA",
        whileOpen: "D11",
        where: "the PSA hop",
        what: "Redis lives in Google’s managed VPC, reached over a second peering",
        why: "Peering does not chain. Traffic cannot cross two peerings, so this can never work.",
        fails: true,
        fixedBy: "D11",
      },
      {
        at: "REDIS",
        whileOpen: "D11",
        where: "never reached",
        what: "No firewall rule or route can change the outcome",
        why: "This is structural, not configuration — which is why the fix is a different path, not a different rule",
        fails: true,
      },
      {
        at: "PARTNER",
        afterClosed: "D11",
        where: "partner-vpc",
        what: "Creates a PSC endpoint in its own network, pointing at a service attachment you publish",
        why: "The endpoint is an IP in their subnet, with their own firewall rules on it",
      },
      {
        at: "PSC",
        afterClosed: "D11",
        where: "service attachment",
        what: "You publish the service and accept their connection explicitly",
        why: "Nothing is peered, so there is no transitivity to run into",
      },
      {
        at: "REDIS",
        afterClosed: "D11",
        where: "reached",
        what: "Traffic arrives without either side exposing anything to the internet",
        why: "This is why PSC would have been the better original choice for the database too",
      },
    ],
  },
];
