// Harbour network track data. Positions are in SVG viewBox units (1580 × 1000 for the map).
import type { ArchNode } from "@/lib/architecture/types";

export const nodes: ArchNode[] = [
  {
    id: "USERS",
    x: 24,
    y: 188,
    w: 168,
    h: 52,
    label: "Shoppers",
    sub: "browser · mobile app",
    kind: "ext",
    layers: ["ingress", "lb"],
  },
  {
    id: "CF",
    x: 24,
    y: 260,
    w: 168,
    h: 56,
    label: "Cloudflare",
    sub: "CDN + WAF",
    kind: "edge",
    layers: ["ingress", "lb", "defects"],
    defects: ["D8"],
  },
  {
    id: "ADMIN",
    x: 24,
    y: 336,
    w: 168,
    h: 52,
    label: "Admin panel",
    sub: "campaign console",
    kind: "ext",
    layers: ["ingress"],
  },
  {
    id: "ONPREM",
    x: 24,
    y: 704,
    w: 168,
    h: 56,
    label: "Office network",
    sub: "192.168.0.0/16",
    kind: "ext",
    dim: true,
    layers: ["routing"],
  },
  {
    id: "PARTNER",
    x: 24,
    y: 862,
    w: 168,
    h: 52,
    label: "partner-vpc",
    sub: "172.20.0.0/16",
    kind: "ext",
    layers: ["routing", "defects"],
    defects: ["D11"],
  },
  {
    id: "DIRECT",
    x: 232,
    y: 188,
    w: 168,
    h: 52,
    label: "Direct run.app URL",
    sub: "skips CDN, LB and WAF",
    kind: "ext",
    layers: ["ingress", "lb", "defects"],
    defects: ["D6"],
  },
  {
    id: "GLB",
    x: 232,
    y: 260,
    w: 168,
    h: 56,
    label: "Global external ALB",
    sub: "+ Cloud Armor",
    kind: "edge",
    layers: ["ingress", "lb", "defects"],
    defects: ["D8"],
  },
  {
    id: "SCHED",
    x: 232,
    y: 336,
    w: 168,
    h: 52,
    label: "Cloud Scheduler",
    sub: "daily cron · OIDC",
    kind: "edge",
    layers: ["ingress"],
  },
  {
    id: "IAP",
    x: 232,
    y: 482,
    w: 168,
    h: 52,
    label: "IAP TCP forwarding",
    sub: "35.235.240.0/20",
    kind: "edge",
    dim: true,
    layers: ["ingress", "access"],
  },
  {
    id: "HC",
    x: 232,
    y: 552,
    w: 168,
    h: 56,
    label: "Health check probes",
    sub: "35.191/16 · 130.211/22",
    kind: "edge",
    layers: ["lb", "firewall"],
  },
  {
    id: "VPN",
    x: 232,
    y: 704,
    w: 168,
    h: 56,
    label: "HA VPN",
    sub: "BGP · dynamic routes · not built",
    kind: "net",
    dim: true,
    layers: ["routing"],
  },
  {
    id: "PEER",
    x: 232,
    y: 862,
    w: 168,
    h: 52,
    label: "VPC peering",
    sub: "active · non-transitive",
    kind: "net",
    layers: ["routing", "defects"],
    defects: ["D11"],
  },
  {
    id: "API",
    x: 490,
    y: 260,
    w: 170,
    h: 56,
    label: "harbour-api",
    sub: "Cloud Run · public API",
    kind: "compute",
    layers: ["ingress", "egress", "firewall", "lb", "defects"],
    defects: ["D6", "D7"],
  },
  {
    id: "WORKER",
    x: 674,
    y: 260,
    w: 170,
    h: 56,
    label: "harbour-worker",
    sub: "Cloud Run · consumer",
    kind: "compute",
    layers: ["egress", "firewall"],
  },
  {
    id: "LEGACY",
    x: 858,
    y: 260,
    w: 164,
    h: 56,
    label: "legacy-api",
    sub: "MIG · external IPs",
    kind: "compute",
    layers: ["egress", "firewall", "lb", "access", "defects"],
    defects: ["D3b"],
  },
  {
    id: "JOBS",
    x: 490,
    y: 332,
    w: 170,
    h: 60,
    label: "harbour-jobs",
    sub: "Cloud Run · nightly",
    kind: "compute",
    layers: ["ingress", "egress", "firewall"],
  },
  {
    id: "ILB",
    x: 858,
    y: 332,
    w: 164,
    h: 60,
    label: "internal ALB",
    sub: "cannot be created",
    kind: "edge",
    dim: true,
    layers: ["ingress", "lb", "defects"],
    defects: ["D12", "D13", "D14"],
  },
  {
    id: "BASTION",
    x: 490,
    y: 480,
    w: 248,
    h: 56,
    label: "bastion",
    sub: "SSH open to 0.0.0.0/0",
    kind: "compute",
    layers: ["ingress", "firewall", "access", "defects"],
    defects: ["D2", "D3a", "D16"],
  },
  {
    id: "RABBIT",
    x: 774,
    y: 480,
    w: 248,
    h: 56,
    label: "rabbitmq-1",
    sub: "broker · private only",
    kind: "compute",
    layers: ["firewall", "private"],
  },
  {
    id: "SNB",
    x: 478,
    y: 712,
    w: 556,
    h: 40,
    label: "sn-b-app · 10.20.0.0/20",
    kind: "net",
    dim: true,
    layers: ["routing"],
  },
  {
    id: "ROUTER",
    x: 464,
    y: 790,
    w: 284,
    h: 52,
    label: "Cloud Router rtr-a",
    sub: "hosts the NAT · no BGP peers",
    kind: "net",
    layers: ["egress", "routing"],
  },
  {
    id: "NAT",
    x: 764,
    y: 790,
    w: 284,
    h: 52,
    label: "Cloud NAT",
    sub: "2 reserved IPs · stable egress",
    kind: "net",
    layers: ["egress"],
  },
  {
    id: "PSA",
    x: 464,
    y: 862,
    w: 284,
    h: 52,
    label: "PSA reservation",
    sub: "10.90.0.0/16 → peering active",
    kind: "net",
    layers: ["private"],
  },
  {
    id: "PSC",
    x: 764,
    y: 862,
    w: 284,
    h: 52,
    label: "PSC endpoints",
    sub: "10.99.0.0/24",
    kind: "net",
    layers: ["private"],
  },
  {
    id: "SQL",
    x: 1212,
    y: 196,
    w: 328,
    h: 58,
    label: "harbour-pg",
    sub: "Cloud SQL · public IP + authorized nets",
    kind: "data",
    layers: ["private", "defects"],
    defects: ["D5"],
  },
  {
    id: "REDIS",
    x: 1212,
    y: 266,
    w: 328,
    h: 44,
    label: "harbour-cache",
    sub: "Memorystore · private IP via PSA",
    kind: "data",
    layers: ["private"],
  },
  {
    id: "SQLR",
    x: 1212,
    y: 320,
    w: 328,
    h: 28,
    label: "read replica · asia-south1",
    kind: "data",
    dim: true,
    layers: ["private"],
  },
  {
    id: "GCS",
    x: 1212,
    y: 430,
    w: 160,
    h: 62,
    label: "Cloud Storage",
    sub: "assets",
    kind: "data",
    layers: ["private", "lb"],
  },
  {
    id: "SECRET",
    x: 1380,
    y: 430,
    w: 160,
    h: 62,
    label: "Secret Manager",
    sub: "config",
    kind: "data",
    layers: ["private"],
  },
  {
    id: "PAY",
    x: 1212,
    y: 570,
    w: 328,
    h: 56,
    label: "PayGate",
    sub: "whitelists our egress IP",
    kind: "ext",
    layers: ["egress"],
  },
  {
    id: "BILL",
    x: 1212,
    y: 638,
    w: 328,
    h: 50,
    label: "Billing API",
    sub: "api.billing.example",
    kind: "ext",
    layers: ["egress"],
  },
  {
    id: "FCM",
    x: 1212,
    y: 700,
    w: 328,
    h: 50,
    label: "Firebase Cloud Messaging",
    sub: "push to devices",
    kind: "ext",
    layers: ["egress"],
  },
  {
    id: "SAAS",
    x: 1200,
    y: 798,
    w: 352,
    h: 56,
    label: "Log vendor",
    sub: "published service · reached by PSC",
    kind: "ext",
    layers: ["private"],
  },
];
