// Each chapter's MDX, by slug. Imported only by the chapter route: anything
// that reaches these imports ships every widget they use.
import type { ChapterLoaders } from "@/lib/content/types";

export const chapters: ChapterLoaders = {
  "the-kade-scenario": () => import("./chapters/00-the-kade-scenario.mdx"),
  "how-a-request-leaves-your-laptop": () => import("./chapters/01-how-a-request-leaves-your-laptop.mdx"),
  "ip-addresses-ipv4": () => import("./chapters/02-ip-addresses-ipv4.mdx"),
  "networks-hosts-and-cidr": () => import("./chapters/03-networks-hosts-and-cidr.mdx"),
  "subnet-masks": () => import("./chapters/04-subnet-masks.mdx"),
  "the-default-gateway": () => import("./chapters/05-the-default-gateway.mdx"),
  "putting-it-together": () => import("./chapters/06-putting-it-together.mdx"),
  "mac-addresses": () => import("./chapters/07-mac-addresses.mdx"),
  "mac-vs-ip-why-we-need-both": () => import("./chapters/08-mac-vs-ip-why-we-need-both.mdx"),
  "arp-from-ip-to-mac": () => import("./chapters/09-arp-from-ip-to-mac.mdx"),
  "nat-sharing-one-public-ip": () => import("./chapters/10-nat-sharing-one-public-ip.mdx"),
  "tcp-ip-osi-models": () => import("./chapters/11-tcp-ip-osi-models.mdx"),
  "how-routing-works-in-depth": () => import("./chapters/12-how-routing-works-in-depth.mdx"),
  "icmp-ping-traceroute": () => import("./chapters/13-icmp-ping-traceroute.mdx"),
  "udp-the-fast-protocol": () => import("./chapters/14-udp-the-fast-protocol.mdx"),
  "anatomy-of-a-udp-datagram": () => import("./chapters/15-anatomy-of-a-udp-datagram.mdx"),
  "tcp-the-reliable-backbone": () => import("./chapters/16-tcp-the-reliable-backbone.mdx"),
  "tcp-sequence-ack-numbers": () => import("./chapters/17-tcp-sequence-ack-numbers.mdx"),
  "tcp-segment-mtu-mss-fragmentation": () => import("./chapters/18-tcp-segment-mtu-mss-fragmentation.mdx"),
  "tcp-flow-control": () => import("./chapters/19-tcp-flow-control.mdx"),
  "tcp-congestion-control": () => import("./chapters/20-tcp-congestion-control.mdx"),
  "sockets-nagle-keepalives-tcp-from-your-code": () => import("./chapters/21-sockets-nagle-keepalives-tcp-from-your-code.mdx"),
  "dns-how-resolution-works": () => import("./chapters/22-dns-how-resolution-works.mdx"),
  "dns-records-email-security": () => import("./chapters/23-dns-records-email-security.mdx"),
  "http-its-versions": () => import("./chapters/24-http-its-versions.mdx"),
  "tls-https": () => import("./chapters/25-tls-https.mdx"),
  "websockets": () => import("./chapters/26-websockets.mdx"),
  "dhcp-in-depth": () => import("./chapters/27-dhcp-in-depth.mdx"),
  "same-origin-policy-cors": () => import("./chapters/28-same-origin-policy-cors.mdx"),
  "ssh-tunnels": () => import("./chapters/29-ssh-tunnels.mdx"),
  "ipv6": () => import("./chapters/30-ipv6.mdx"),
  "ports-sockets": () => import("./chapters/31-ports-sockets.mdx"),
  "hubs-switches-routers": () => import("./chapters/32-hubs-switches-routers.mdx"),
  "proxies-reverse-proxies-load-balancers": () => import("./chapters/33-proxies-reverse-proxies-load-balancers.mdx"),
  "capstone-opening-api-kade-lk": () => import("./chapters/34-capstone-opening-api-kade-lk.mdx"),
};
