// Generated by doc/tools/convert.py from the course notes; edit freely once
// the migration is done. A chapter is published when it has `Content`.
import type { Course } from "@/lib/content/types";
import Ch0 from "./chapters/00-the-kade-scenario.mdx";
import Ch1 from "./chapters/01-how-a-request-leaves-your-laptop.mdx";
import Ch2 from "./chapters/02-ip-addresses-ipv4.mdx";
import Ch3 from "./chapters/03-networks-hosts-and-cidr.mdx";
import Ch4 from "./chapters/04-subnet-masks.mdx";
import Ch5 from "./chapters/05-the-default-gateway.mdx";
import Ch6 from "./chapters/06-putting-it-together.mdx";
import Ch7 from "./chapters/07-mac-addresses.mdx";
import Ch8 from "./chapters/08-mac-vs-ip-why-we-need-both.mdx";
import Ch9 from "./chapters/09-arp-from-ip-to-mac.mdx";
import Ch10 from "./chapters/10-nat-sharing-one-public-ip.mdx";
import Ch11 from "./chapters/11-tcp-ip-osi-models.mdx";
import Ch12 from "./chapters/12-how-routing-works-in-depth.mdx";
import Ch13 from "./chapters/13-icmp-ping-traceroute.mdx";
import Ch14 from "./chapters/14-udp-the-fast-protocol.mdx";
import Ch15 from "./chapters/15-anatomy-of-a-udp-datagram.mdx";
import Ch16 from "./chapters/16-tcp-the-reliable-backbone.mdx";
import Ch17 from "./chapters/17-tcp-sequence-ack-numbers.mdx";
import Ch18 from "./chapters/18-tcp-segment-mtu-mss-fragmentation.mdx";
import Ch19 from "./chapters/19-tcp-flow-control.mdx";
import Ch20 from "./chapters/20-tcp-congestion-control.mdx";
import Ch21 from "./chapters/21-sockets-nagle-keepalives-tcp-from-your-code.mdx";
import Ch22 from "./chapters/22-dns-how-resolution-works.mdx";
import Ch23 from "./chapters/23-dns-records-email-security.mdx";
import Ch24 from "./chapters/24-http-its-versions.mdx";
import Ch25 from "./chapters/25-tls-https.mdx";
import Ch26 from "./chapters/26-websockets.mdx";
import Ch27 from "./chapters/27-dhcp-in-depth.mdx";
import Ch28 from "./chapters/28-same-origin-policy-cors.mdx";
import Ch29 from "./chapters/29-ssh-tunnels.mdx";
import Ch30 from "./chapters/30-ipv6.mdx";
import Ch31 from "./chapters/31-ports-sockets.mdx";
import Ch32 from "./chapters/32-hubs-switches-routers.mdx";
import Ch33 from "./chapters/33-proxies-reverse-proxies-load-balancers.mdx";
import Ch34 from "./chapters/34-capstone-opening-api-kade-lk.mdx";

export const fundamentals: Course = {
  slug: "fundamentals",
  title: "Networking fundamentals",
  short: "Fundamentals",
  summary: "From a fetch() call to bytes on the wire, and beyond.",
  legend: {
  },
  parts: [
    { id: "start-here", title: "Start here" },
    { id: "addressing-and-local-delivery", title: "Addressing and local delivery" },
    { id: "layers-routing-and-transport", title: "Layers, routing and transport" },
    { id: "application-protocols", title: "Application protocols" },
    { id: "network-building-blocks", title: "Network building blocks" },
    { id: "putting-it-together", title: "Putting it together" },
  ],
  chapters: [
    {
      num: "0",
      slug: "the-kade-scenario",
      title: "The Kadé scenario",
      lead: "Every chapter uses the same small company and the same addresses, so each new idea lands on something you have already seen. Come back to this page whenever an address looks unfamiliar.",
      part: "start-here",
      minutes: 3,
      Content: Ch0,
    },
    {
      num: "1",
      slug: "how-a-request-leaves-your-laptop",
      title: "How a request leaves your laptop",
      lead: "One line of JavaScript calls a server in the cloud. This chapter follows that call from the browser until it leaves your laptop as a signal. Each topic here gets its own deep-dive chapter later.",
      part: "addressing-and-local-delivery",
      minutes: 10,
      Content: Ch1,
    },
    {
      num: "2",
      slug: "ip-addresses-ipv4",
      title: "IP addresses (IPv4)",
      lead: "In chapter 1 the laptop was 192.168.1.23 and Kadé's API was 34.87.120.15. This chapter opens up those numbers: what they are, how a computer stores them, and which ones have special jobs.",
      part: "addressing-and-local-delivery",
      minutes: 6,
      Content: Ch2,
    },
    {
      num: "3",
      slug: "networks-hosts-and-cidr",
      title: "Networks, hosts and CIDR",
      lead: "Chapter 2 looked at one address. This chapter looks at groups of them: what a network is, how devices get their address, and how CIDR describes a whole range in one short line.",
      part: "addressing-and-local-delivery",
      minutes: 7,
      Content: Ch3,
    },
    {
      num: "4",
      slug: "subnet-masks",
      title: "Subnet masks",
      lead: "CIDR says where the network part ends. The subnet mask is how a machine actually uses that split, many times a second, to decide where each packet goes.",
      part: "addressing-and-local-delivery",
      minutes: 5,
      Content: Ch4,
    },
    {
      num: "5",
      slug: "the-default-gateway",
      title: "The default gateway",
      lead: "Chapter 4 ended with a decision: same network, send directly; different network, send to the gateway. This chapter is about that gateway: what it is, where your laptop learns about it, and what happens after the packet reaches it.",
      part: "addressing-and-local-delivery",
      minutes: 5,
      Content: Ch5,
    },
    {
      num: "6",
      slug: "putting-it-together",
      title: "Putting it together",
      lead: "Kadé opens an office with a small warehouse at the back. Two networks, one router between them. We follow three messages and watch every decision from chapters 2 to 5 happen in order.",
      part: "addressing-and-local-delivery",
      minutes: 4,
      Content: Ch6,
    },
    {
      num: "7",
      slug: "mac-addresses",
      title: "MAC addresses",
      lead: "Chapters 2 to 6 were about IP addresses. But the frame in chapter 1 also carried a second kind of address, and the router's MAC kept coming up in every chapter since. This chapter explains what that address is.",
      part: "addressing-and-local-delivery",
      minutes: 6,
      Content: Ch7,
    },
    {
      num: "8",
      slug: "mac-vs-ip-why-we-need-both",
      title: "MAC vs IP: why we need both",
      lead: "Every interface has two addresses. This chapter puts them side by side and shows why neither one can do the other's job.",
      part: "addressing-and-local-delivery",
      minutes: 3,
      Content: Ch8,
    },
    {
      num: "9",
      slug: "arp-from-ip-to-mac",
      title: "ARP: from IP to MAC",
      lead: "A device always knows the IP it wants to reach, but the frame needs a MAC. ARP fills that gap. It is one of the simplest protocols in networking, and it runs before almost every conversation on a local network.",
      part: "addressing-and-local-delivery",
      minutes: 5,
      Content: Ch9,
    },
    {
      num: "10",
      slug: "nat-sharing-one-public-ip",
      title: "NAT: sharing one public IP",
      lead: "Every home and office in this course uses private addresses, yet all of them reach kade-api. This chapter explains the swap that makes that work, its limits and side effects, and how it is done in GCP. It is a big reason IPv4 is still in use.",
      part: "addressing-and-local-delivery",
      minutes: 13,
      Content: Ch10,
    },
    {
      num: "11",
      slug: "tcp-ip-osi-models",
      title: "TCP/IP & OSI models",
      lead: "Section 1 built up one piece at a time: IP, masks, gateways, MAC, ARP, NAT. This chapter gives those pieces a place. Layers are the map every later chapter hangs on.",
      part: "layers-routing-and-transport",
      minutes: 6,
      Content: Ch11,
    },
    {
      num: "12",
      slug: "how-routing-works-in-depth",
      title: "How routing works (in depth)",
      lead: "Chapter 5 stopped at \"the gateway passes it on\". This chapter follows one packet from the Kadé office to kade-api through every router on the way, and shows each decision and every field that changes.",
      part: "layers-routing-and-transport",
      minutes: 12,
      Content: Ch12,
    },
    {
      num: "13",
      slug: "icmp-ping-traceroute",
      title: "ICMP: ping & traceroute",
      lead: "When a packet is dropped, someone should say why. ICMP is how routers and hosts report problems, and two of the most used debugging tools, ping and traceroute, are built on it.",
      part: "layers-routing-and-transport",
      minutes: 8,
      Content: Ch13,
    },
    {
      num: "14",
      slug: "udp-the-fast-protocol",
      title: "UDP: the fast protocol",
      lead: "Chapters 12 and 13 got a packet to the right machine. The Transport layer gets it to the right program. There are two main choices: UDP, which just sends, and TCP, which guarantees delivery. This chapter is about the first.",
      part: "layers-routing-and-transport",
      minutes: 7,
      Content: Ch14,
    },
    {
      num: "15",
      slug: "anatomy-of-a-udp-datagram",
      title: "Anatomy of a UDP datagram",
      lead: "Everything UDP does fits in 8 bytes. This chapter opens those bytes one field at a time, using a real datagram: your laptop asking the home router \"what is the IP of api.kade.lk?\".",
      part: "layers-routing-and-transport",
      minutes: 6,
      Content: Ch15,
    },
    {
      num: "16",
      slug: "tcp-the-reliable-backbone",
      title: "TCP: the reliable backbone",
      lead: "Almost everything Kadé does that must not go wrong runs over TCP: every order sent to kade-api, every query to kade-db, every call to PayGate. This chapter covers what TCP promises, how a connection opens and closes, and the states you will see when debugging.",
      part: "layers-routing-and-transport",
      minutes: 7,
      Content: Ch16,
    },
    {
      num: "17",
      slug: "tcp-sequence-ack-numbers",
      title: "TCP sequence & ACK numbers",
      lead: "Two numbers on every segment are the whole secret of TCP's reliability. Once you can read them, you can follow any TCP conversation in tcpdump or Wireshark, and see exactly where it went wrong.",
      part: "layers-routing-and-transport",
      minutes: 5,
      Content: Ch17,
    },
    {
      num: "18",
      slug: "tcp-segment-mtu-mss-fragmentation",
      title: "TCP segment, MTU, MSS & fragmentation",
      lead: "This chapter opens the TCP header field by field, then follows the question every sender has to answer: how big can each piece be? That leads to MTU, MSS, fragmentation and path MTU discovery, and to one of the most confusing bugs in networking.",
      part: "layers-routing-and-transport",
      minutes: 9,
      Content: Ch18,
    },
    {
      num: "19",
      slug: "tcp-flow-control",
      title: "TCP flow control",
      lead: "TCP can send data faster than some programs can read it. Flow control is how the receiver says \"slow down, I'm full\", using a number carried in every segment. The same idea shows up in your own code as backpressure.",
      part: "layers-routing-and-transport",
      minutes: 5,
      Content: Ch19,
    },
    {
      num: "20",
      slug: "tcp-congestion-control",
      title: "TCP congestion control",
      lead: "Flow control protects the receiver. This chapter is about protecting everyone else: the shared links in between. TCP cannot see the network, so it has to guess how much it may send, and it does so with a few simple rules that keep the whole internet working.",
      part: "layers-routing-and-transport",
      minutes: 7,
      Content: Ch20,
    },
    {
      num: "21",
      slug: "sockets-nagle-keepalives-tcp-from-your-code",
      title: "Sockets, Nagle & keepalives: TCP from your code",
      lead: "Chapters 16-20 described TCP from the network's side. This chapter looks at the same things from kade-api's code: the calls your app makes, the queues it can overflow, a 40 ms delay hiding in small writes, and the timeouts that quietly kill idle connections.",
      part: "layers-routing-and-transport",
      minutes: 8,
      Content: Ch21,
    },
    {
      num: "22",
      slug: "dns-how-resolution-works",
      title: "DNS: how resolution works",
      lead: "Chapter 1 started with the browser asking \"where is api.kade.lk?\" and getting 34.87.120.15. This chapter opens that step fully: who is asked, in what order, why the second lookup is faster than the first, and where it can go wrong.",
      part: "application-protocols",
      minutes: 10,
      Content: Ch22,
    },
    {
      num: "23",
      slug: "dns-records-email-security",
      title: "DNS records & email security",
      lead: "Setting up a domain is mostly creating the right records. This chapter builds Kadé's kade.lk zone record by record, then uses DNS to solve a real problem: stopping criminals from sending fake emails as \"payments@kade.lk\".",
      part: "application-protocols",
      minutes: 10,
      Content: Ch23,
    },
    {
      num: "24",
      slug: "http-its-versions",
      title: "HTTP & its versions",
      lead: "Chapter 1 showed one HTTP request as text. This chapter covers the whole protocol: what requests and responses contain, how status codes and headers work, how a stateless protocol remembers who you are, and how HTTP/1.1, HTTP/2 and HTTP/3 carry the same messages in faster ways.",
      part: "application-protocols",
      minutes: 9,
      Content: Ch24,
    },
    {
      num: "25",
      slug: "tls-https",
      title: "TLS & HTTPS",
      lead: "Every request to api.kade.lk carries passwords, addresses and order details. TLS is what stops the café WiFi, the ISP, or anyone in between from reading or changing them, and what proves the laptop is really talking to Kadé. This chapter builds it up from the crypto basics to the certificates on kade-api.",
      part: "application-protocols",
      minutes: 12,
      Content: Ch25,
    },
    {
      num: "26",
      slug: "websockets",
      title: "WebSockets",
      lead: "Kadé wants live order tracking: the shopper's app should show the rider moving on the map and the status changing the moment it happens. Plain HTTP cannot push anything to the app. This chapter covers the options, then WebSockets in depth: the handshake, the frames, and what it takes to run them in production.",
      part: "application-protocols",
      minutes: 8,
      Content: Ch26,
    },
    {
      num: "27",
      slug: "dhcp-in-depth",
      title: "DHCP in depth",
      lead: "Chapter 3 introduced DHCP: four messages, and the laptop gets its IP, mask, gateway and DNS server. This chapter looks at the real packets, what happens over a lease's lifetime, how one DHCP server can serve both of Kadé's office networks, and how DHCP can be attacked.",
      part: "application-protocols",
      minutes: 9,
      Content: Ch27,
    },
    {
      num: "28",
      slug: "same-origin-policy-cors",
      title: "Same-origin policy & CORS",
      lead: "The Kadé website at kade.lk calls kade-api at api.kade.lk. The browser treats those as two different origins, and by default it will not let the page read the API's responses. This chapter explains the rule behind that, the CORS headers that relax it safely, and the bugs every web backend developer meets.",
      part: "application-protocols",
      minutes: 8,
      Content: Ch28,
    },
    {
      num: "29",
      slug: "ssh-tunnels",
      title: "SSH & tunnels",
      lead: "As Kadé's engineer you log in to kade-api to read logs, and you need to query kade-db, which has no public address at all. SSH does both: a secure remote shell, and encrypted tunnels that carry other connections through it. This chapter covers how SSH works, keys, the three kinds of tunnels, and how GCP lets you reach VMs without opening port 22 to the internet.",
      part: "application-protocols",
      minutes: 8,
      Content: Ch29,
    },
    {
      num: "30",
      slug: "ipv6",
      title: "IPv6",
      lead: "Chapter 2 ended with IPv4 running out of addresses, and chapter 10 showed NAT as the workaround. IPv6 is the permanent fix. This chapter covers its addresses, how devices configure themselves without DHCP, how it replaces ARP and broadcast, and how it runs alongside IPv4 today.",
      part: "network-building-blocks",
      minutes: 9,
      Content: Ch30,
    },
    {
      num: "31",
      slug: "ports-sockets",
      title: "Ports & sockets",
      lead: "An IP address gets a packet to the right machine. But kade-api runs Node, an SSH server, a monitoring agent and more, all using the network at once. Ports decide which program gets each packet. This chapter brings together what earlier chapters used piece by piece: port numbers, well-known ports, sockets, bind addresses, and how the 4-tuple keeps every connection apart.",
      part: "network-building-blocks",
      minutes: 7,
      Content: Ch31,
    },
    {
      num: "32",
      slug: "hubs-switches-routers",
      title: "Hubs, switches & routers",
      lead: "Chapter 6 showed the office router and switch as boxes on a map. This chapter opens them up: what a hub, a switch and a router each do with an arriving frame, how a switch learns where devices are, and why routers are the walls that keep broadcasts contained.",
      part: "network-building-blocks",
      minutes: 7,
      Content: Ch32,
    },
    {
      num: "33",
      slug: "proxies-reverse-proxies-load-balancers",
      title: "Proxies, reverse proxies & load balancers",
      lead: "Since chapter 1, the laptop talked straight to kade-api. Real services almost never work like that: something sits in the middle. This chapter explains those middle boxes, gives Kadé its load balancer, and brings together pieces from earlier chapters: TLS termination (25), 502s from keep-alive races (21), 5xx codes (24), WebSocket timeouts (26) and NAT's hidden clients (10).",
      part: "putting-it-together",
      minutes: 16,
      Content: Ch33,
    },
    {
      num: "34",
      slug: "capstone-opening-api-kade-lk",
      title: "Capstone: opening api.kade.lk",
      lead: "Chapter 1 followed one request in broad strokes. Thirty-three chapters later, we can follow it properly: every packet, every header that changes, every box it passes through, and how long each part takes. You open the Kadé order page at home, and the app calls https://api.kade.lk/orders/1042.",
      part: "putting-it-together",
      minutes: 8,
      Content: Ch34,
    },
  ],
};
